name : Email Summary Bot

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:

jobs:
  run-bot:
    runs-on : ubuntu-latest

    steps:
      - name : checkout
        uses : actions/checkout@v3


      - name : Set up Python
        uses : actions/setup-python@v4
        with:
          python-version: '3.12'

      - name : Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write tokens.json from secret
        run: echo '${{ secrets.GMAIL_TOKENS_JSON }}' > tokens.json


      - name : Run bot
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

        run: |
          python main.py